---
title: "Estadística Multivariante - PEC 2"
author: "Alejandro Keymer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Prueba de evaluación continua 2Estadística MultivarianteFrancesc Carmona4 de enero de 2020El bosque de Woodyard HammockVamos a trabajar el análisis de conglomerados con los datos ecológicos de Woodyard Hammock, un bosquede magnolias y hayas en el norte de Florida.Los datos son el recuento del número de árboles de cada especie enn= 72lugares. Se identificarony contabilizaron un total de 31 especies, sin embargo, solo trabajaremos con lasp= 13especies máscomunes que se indican a continuación:carcarCarpinus carolinianaIronwoodcorfloCornus floridaDogwoodfaggraFagus grandifoliaBeechileopaIlex opacaHollyliqstyLiquidambar styracifluaSweetgummaggraMagnolia grandifloraMagnolianyssylNyssa sylvaticaBlackgumostvirOstrya virginianaBlue BeechoxyarbOxydendrum arboreumSourwoodpinglaPinus glabraSpruce PinequenigQuercus nigraWater OakquemicQuercus michauxiiSwamp Chestnut OaksymtinSymplocus tinctoriaHorse SugarMagnoliaMagnolia grandifloraLa primera columna da un código de identificación de la especie con seis letras, la segunda columna dasu nombre científico en nomenclatura binomial y la tercera columna da el nombre común (en inglés) decada especie. Los árboles más frecuentes en este bosque son las hayas y las magnolias.Los datos se hallan en el archivowood.datque se encuentra en la web del curso STAT 505AppliedMultivariate Statistical Analysisdel Eberly College of Science de la Universidad de Pennsylvania1Ejercicio 1 (70 pt.)(a) Después de reducir la base de datos original a lasp= 13especies destacadas, nos planteamos elegiruna distancia adecuada para el análisis de conglomerados. Con este tipo de datos se suele utilizar1https://newonlinecourses.science.psu.edu/stat505/lesson/14/14.1
la disimilaridad de Bray-Curtis con la siguiente fórmula según la Wikipedia:d(1)BC(i,j) = 1−2CijSi+SjdondeCijes la suma del menor valor para cada una de las especies en común de las dos muestras.SiySjson el total de especímenes en cada una de las muestras.También se puede calcular con la fórmula que utiliza la funciónvegdist()del paquetevegan:d(2)BC(i,j) =∑pk=1|xik−xjk|∑pk=1(xik+xjk)Calcular la disimilaridad de Bray-Curtis entre las dos primeras muestras de la base de datos conambas fórmulas (sin utilizar la funciónvegdist()). En la primera fórmula nos puede ayudar lafunciónpmin()deR.Calcular a continuación la matriz de disimilaridades completa con la funciónvegdist()y compro-bamos que el valor hallado para las dos primeras muestras coincide.(b) Sin embargo, la disimilaridad de Bray-Curtis no verifica la desigualdad triangular de forma que noes una distancia. Comprobar este hecho, tal vez con algún contraejemplo entre dos muestras o conalguna función deRque podamos hallar2.Para corregir este problema podemos transformar la disimilaridad de Bray-Curtis calculando la raízcuadrada de sus valores. Comprobar que dicha raíz cuadrada verifica la desigualdad triangular.(c) Muchos procedimientos de Análisis multivariante requieren que la distancia utilizada sea euclídea.Comprobar que la raíz cuadrada de la disimilaridad de Bray-Curtis es una distancia euclídea.(d) Evaluar la tendencia al agrupamiento con el estadístico de Hopkins que podéis calcular con lafunciónget_clust_tendency()del paquetefactoextra3.La funciónfviz_dist()del mismo paquete permite realizar una imagen de la disimilaridad pro-puesta en el apartado anterior (ordered dissimilarity image, ODI) para evaluar gráficamente la2No hay que programar. Se puede hallar una función en un cierto paquete y otra que mejora la anterior.3Un estadístico recíproco se puede calcular con la funciónhopkins()del paqueteclustertend.Página 2 de 4
tendencia al agrupamiento. También la misma funciónget_clust_tendency()lo hace con unaimagen menos vistosa. ¿Cuantos conglomerados se intuyen?Para saber más sobre el análisis de la tendencia al agrupamiento, la fórmula del estadístico deHopkins y un ejemplo se puede consultar la páginahttps://www.datanovia.com/en/lessons/assessing-clustering-tendency/Nota: Un valor alto del estadístico de Hopkins nos permitirá realizar el análisis de conglomeradoscon la confianza de que los grupos estarán bastante bien formados. Un valor bajo nos dice que laformación de los conglomerados será mucho más difícil y no tan clara.(e) Realizar un análisis de conglomerados jerárquico con el método de Ward4de la distancia propuestaen el apartado (c). Dibujar el dendograma resultante.Nota: Justamente el método de Ward exige que la distancia sea euclídea, pero no necesariamentela distancia euclídea.Dibujar también unheatmapde este análisis con la funciónheatmap(). Para ello, hay que elegirbien los parámetrosdistfun=yhclustfun=y una escala de colores. ¿Para qué sirve elheatmap?Nota: No nos interesa reordenar las variables o columnas y tampoco un dendograma sobre ellas.(f) El siguiente paso es estudiar por algún criterio el número óptimo de conglomerados para el análisisjerárquico. Con la distancia del apartado (c) en particular, lo más sencillo es utilizar el criterio delas siluetas.Sin embargo, el criterio de las siluetas y otros métodos como el de la suma de cuadrados dentro delos grupos o WSS o también el estadístico GAP se pueden aplicar con la funciónfviz_nbclust()del paquetefactoextra. Habrá que especificar que se trata del método de clasificación jerárquico(que por defecto utiliza el método de Ward) y también la distancia raíz cuadrada de la disimilaridadde Bray-Curtis.(g) Estudiar con la misma distancia el número óptimo de conglomerados con el método PAM.(h) De los apartados anteriores se deduce que no hay un número claro de conglomerados. Un ecólogoexperto propone que sean 6, ya que su experiencia así lo ha visto en otros bosques similares. Dibujarel dendograma del apartado (e) con esta partición.Con el objetivo de caracterizar los conglomerados, calcular una tabla con las medianas de las fre-cuencias de cada especie en cada uno de los seis conglomerados del dendograma anterior. Descartarde esta tabla las especies con una mediana inferior o igual a 4 en todos los conglomerados.Representar la tabla anterior con un análisis de correspondencias y un gráfico asimétrico.4Se puede utilizar la funciónhclust()o la funciónagnes().Página 3 de 4
